# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andres/src/Gamma

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andres/src/Gamma

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andres/src/Gamma/CMakeFiles /home/andres/src/Gamma/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andres/src/Gamma/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Gamma

# Build rule for target.
Gamma: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Gamma
.PHONY : Gamma

# fast build rule for target.
Gamma/fast:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/build
.PHONY : Gamma/fast

src/AudioIO.o: src/AudioIO.cpp.o
.PHONY : src/AudioIO.o

# target to build an object file
src/AudioIO.cpp.o:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/AudioIO.cpp.o
.PHONY : src/AudioIO.cpp.o

src/AudioIO.i: src/AudioIO.cpp.i
.PHONY : src/AudioIO.i

# target to preprocess a source file
src/AudioIO.cpp.i:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/AudioIO.cpp.i
.PHONY : src/AudioIO.cpp.i

src/AudioIO.s: src/AudioIO.cpp.s
.PHONY : src/AudioIO.s

# target to generate assembly for a file
src/AudioIO.cpp.s:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/AudioIO.cpp.s
.PHONY : src/AudioIO.cpp.s

src/Conversion.o: src/Conversion.cpp.o
.PHONY : src/Conversion.o

# target to build an object file
src/Conversion.cpp.o:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/Conversion.cpp.o
.PHONY : src/Conversion.cpp.o

src/Conversion.i: src/Conversion.cpp.i
.PHONY : src/Conversion.i

# target to preprocess a source file
src/Conversion.cpp.i:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/Conversion.cpp.i
.PHONY : src/Conversion.cpp.i

src/Conversion.s: src/Conversion.cpp.s
.PHONY : src/Conversion.s

# target to generate assembly for a file
src/Conversion.cpp.s:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/Conversion.cpp.s
.PHONY : src/Conversion.cpp.s

src/DFT.o: src/DFT.cpp.o
.PHONY : src/DFT.o

# target to build an object file
src/DFT.cpp.o:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/DFT.cpp.o
.PHONY : src/DFT.cpp.o

src/DFT.i: src/DFT.cpp.i
.PHONY : src/DFT.i

# target to preprocess a source file
src/DFT.cpp.i:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/DFT.cpp.i
.PHONY : src/DFT.cpp.i

src/DFT.s: src/DFT.cpp.s
.PHONY : src/DFT.s

# target to generate assembly for a file
src/DFT.cpp.s:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/DFT.cpp.s
.PHONY : src/DFT.cpp.s

src/FFT_fftpack.o: src/FFT_fftpack.cpp.o
.PHONY : src/FFT_fftpack.o

# target to build an object file
src/FFT_fftpack.cpp.o:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/FFT_fftpack.cpp.o
.PHONY : src/FFT_fftpack.cpp.o

src/FFT_fftpack.i: src/FFT_fftpack.cpp.i
.PHONY : src/FFT_fftpack.i

# target to preprocess a source file
src/FFT_fftpack.cpp.i:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/FFT_fftpack.cpp.i
.PHONY : src/FFT_fftpack.cpp.i

src/FFT_fftpack.s: src/FFT_fftpack.cpp.s
.PHONY : src/FFT_fftpack.s

# target to generate assembly for a file
src/FFT_fftpack.cpp.s:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/FFT_fftpack.cpp.s
.PHONY : src/FFT_fftpack.cpp.s

src/File.o: src/File.cpp.o
.PHONY : src/File.o

# target to build an object file
src/File.cpp.o:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/File.cpp.o
.PHONY : src/File.cpp.o

src/File.i: src/File.cpp.i
.PHONY : src/File.i

# target to preprocess a source file
src/File.cpp.i:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/File.cpp.i
.PHONY : src/File.cpp.i

src/File.s: src/File.cpp.s
.PHONY : src/File.s

# target to generate assembly for a file
src/File.cpp.s:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/File.cpp.s
.PHONY : src/File.cpp.s

src/Print.o: src/Print.cpp.o
.PHONY : src/Print.o

# target to build an object file
src/Print.cpp.o:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/Print.cpp.o
.PHONY : src/Print.cpp.o

src/Print.i: src/Print.cpp.i
.PHONY : src/Print.i

# target to preprocess a source file
src/Print.cpp.i:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/Print.cpp.i
.PHONY : src/Print.cpp.i

src/Print.s: src/Print.cpp.s
.PHONY : src/Print.s

# target to generate assembly for a file
src/Print.cpp.s:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/Print.cpp.s
.PHONY : src/Print.cpp.s

src/Recorder.o: src/Recorder.cpp.o
.PHONY : src/Recorder.o

# target to build an object file
src/Recorder.cpp.o:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/Recorder.cpp.o
.PHONY : src/Recorder.cpp.o

src/Recorder.i: src/Recorder.cpp.i
.PHONY : src/Recorder.i

# target to preprocess a source file
src/Recorder.cpp.i:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/Recorder.cpp.i
.PHONY : src/Recorder.cpp.i

src/Recorder.s: src/Recorder.cpp.s
.PHONY : src/Recorder.s

# target to generate assembly for a file
src/Recorder.cpp.s:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/Recorder.cpp.s
.PHONY : src/Recorder.cpp.s

src/Scheduler.o: src/Scheduler.cpp.o
.PHONY : src/Scheduler.o

# target to build an object file
src/Scheduler.cpp.o:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/Scheduler.cpp.o
.PHONY : src/Scheduler.cpp.o

src/Scheduler.i: src/Scheduler.cpp.i
.PHONY : src/Scheduler.i

# target to preprocess a source file
src/Scheduler.cpp.i:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/Scheduler.cpp.i
.PHONY : src/Scheduler.cpp.i

src/Scheduler.s: src/Scheduler.cpp.s
.PHONY : src/Scheduler.s

# target to generate assembly for a file
src/Scheduler.cpp.s:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/Scheduler.cpp.s
.PHONY : src/Scheduler.cpp.s

src/SoundFile.o: src/SoundFile.cpp.o
.PHONY : src/SoundFile.o

# target to build an object file
src/SoundFile.cpp.o:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/SoundFile.cpp.o
.PHONY : src/SoundFile.cpp.o

src/SoundFile.i: src/SoundFile.cpp.i
.PHONY : src/SoundFile.i

# target to preprocess a source file
src/SoundFile.cpp.i:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/SoundFile.cpp.i
.PHONY : src/SoundFile.cpp.i

src/SoundFile.s: src/SoundFile.cpp.s
.PHONY : src/SoundFile.s

# target to generate assembly for a file
src/SoundFile.cpp.s:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/SoundFile.cpp.s
.PHONY : src/SoundFile.cpp.s

src/Sync.o: src/Sync.cpp.o
.PHONY : src/Sync.o

# target to build an object file
src/Sync.cpp.o:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/Sync.cpp.o
.PHONY : src/Sync.cpp.o

src/Sync.i: src/Sync.cpp.i
.PHONY : src/Sync.i

# target to preprocess a source file
src/Sync.cpp.i:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/Sync.cpp.i
.PHONY : src/Sync.cpp.i

src/Sync.s: src/Sync.cpp.s
.PHONY : src/Sync.s

# target to generate assembly for a file
src/Sync.cpp.s:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/Sync.cpp.s
.PHONY : src/Sync.cpp.s

src/arr.o: src/arr.cpp.o
.PHONY : src/arr.o

# target to build an object file
src/arr.cpp.o:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/arr.cpp.o
.PHONY : src/arr.cpp.o

src/arr.i: src/arr.cpp.i
.PHONY : src/arr.i

# target to preprocess a source file
src/arr.cpp.i:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/arr.cpp.i
.PHONY : src/arr.cpp.i

src/arr.s: src/arr.cpp.s
.PHONY : src/arr.s

# target to generate assembly for a file
src/arr.cpp.s:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/arr.cpp.s
.PHONY : src/arr.cpp.s

src/fftpack++1.o: src/fftpack++1.cpp.o
.PHONY : src/fftpack++1.o

# target to build an object file
src/fftpack++1.cpp.o:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/fftpack++1.cpp.o
.PHONY : src/fftpack++1.cpp.o

src/fftpack++1.i: src/fftpack++1.cpp.i
.PHONY : src/fftpack++1.i

# target to preprocess a source file
src/fftpack++1.cpp.i:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/fftpack++1.cpp.i
.PHONY : src/fftpack++1.cpp.i

src/fftpack++1.s: src/fftpack++1.cpp.s
.PHONY : src/fftpack++1.s

# target to generate assembly for a file
src/fftpack++1.cpp.s:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/fftpack++1.cpp.s
.PHONY : src/fftpack++1.cpp.s

src/fftpack++2.o: src/fftpack++2.cpp.o
.PHONY : src/fftpack++2.o

# target to build an object file
src/fftpack++2.cpp.o:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/fftpack++2.cpp.o
.PHONY : src/fftpack++2.cpp.o

src/fftpack++2.i: src/fftpack++2.cpp.i
.PHONY : src/fftpack++2.i

# target to preprocess a source file
src/fftpack++2.cpp.i:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/fftpack++2.cpp.i
.PHONY : src/fftpack++2.cpp.i

src/fftpack++2.s: src/fftpack++2.cpp.s
.PHONY : src/fftpack++2.s

# target to generate assembly for a file
src/fftpack++2.cpp.s:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/fftpack++2.cpp.s
.PHONY : src/fftpack++2.cpp.s

src/scl.o: src/scl.cpp.o
.PHONY : src/scl.o

# target to build an object file
src/scl.cpp.o:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/scl.cpp.o
.PHONY : src/scl.cpp.o

src/scl.i: src/scl.cpp.i
.PHONY : src/scl.i

# target to preprocess a source file
src/scl.cpp.i:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/scl.cpp.i
.PHONY : src/scl.cpp.i

src/scl.s: src/scl.cpp.s
.PHONY : src/scl.s

# target to generate assembly for a file
src/scl.cpp.s:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/src/scl.cpp.s
.PHONY : src/scl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Gamma"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/AudioIO.o"
	@echo "... src/AudioIO.i"
	@echo "... src/AudioIO.s"
	@echo "... src/Conversion.o"
	@echo "... src/Conversion.i"
	@echo "... src/Conversion.s"
	@echo "... src/DFT.o"
	@echo "... src/DFT.i"
	@echo "... src/DFT.s"
	@echo "... src/FFT_fftpack.o"
	@echo "... src/FFT_fftpack.i"
	@echo "... src/FFT_fftpack.s"
	@echo "... src/File.o"
	@echo "... src/File.i"
	@echo "... src/File.s"
	@echo "... src/Print.o"
	@echo "... src/Print.i"
	@echo "... src/Print.s"
	@echo "... src/Recorder.o"
	@echo "... src/Recorder.i"
	@echo "... src/Recorder.s"
	@echo "... src/Scheduler.o"
	@echo "... src/Scheduler.i"
	@echo "... src/Scheduler.s"
	@echo "... src/SoundFile.o"
	@echo "... src/SoundFile.i"
	@echo "... src/SoundFile.s"
	@echo "... src/Sync.o"
	@echo "... src/Sync.i"
	@echo "... src/Sync.s"
	@echo "... src/arr.o"
	@echo "... src/arr.i"
	@echo "... src/arr.s"
	@echo "... src/fftpack++1.o"
	@echo "... src/fftpack++1.i"
	@echo "... src/fftpack++1.s"
	@echo "... src/fftpack++2.o"
	@echo "... src/fftpack++2.i"
	@echo "... src/fftpack++2.s"
	@echo "... src/scl.o"
	@echo "... src/scl.i"
	@echo "... src/scl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

